# Generated by Django 3.1.7 on 2021-04-05 13:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0027_auto_20200605_2310'),
    ]

    operations = [
        migrations.RenameField(
            model_name='vinfo',
            old_name='Kitchen',
            new_name='Shop',
        ),
    ]
