# Generated by Django 3.1.7 on 2021-04-05 14:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0029_vendoradd_category'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='vendoradd',
            name='Category',
        ),
        migrations.AddField(
            model_name='vinfo',
            name='Category',
            field=models.CharField(choices=[('Grocery', 'Grocery'), ('Dairy', 'Dairy'), ('Electronics', 'Electronics'), ('Food', 'Food')], default='Food', max_length=255),
            preserve_default=False,
        ),
    ]
