# Generated by Django 3.1.7 on 2021-04-07 16:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0030_auto_20210405_2011'),
    ]

    operations = [
        migrations.AddField(
            model_name='cinfo',
            name='is_verified',
            field=models.BooleanField(default=False),
        ),
    ]
