# Generated by Django 3.1.7 on 2021-04-07 17:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0031_cinfo_is_verified'),
    ]

    operations = [
        migrations.AddField(
            model_name='cinfo',
            name='otp',
            field=models.IntegerField(default=1234),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='vinfo',
            name='is_verified',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='vinfo',
            name='otp',
            field=models.IntegerField(default=123),
            preserve_default=False,
        ),
    ]
