# Generated by Django 3.1.7 on 2021-04-07 17:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0032_auto_20210407_2258'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cinfo',
            name='otp',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='vinfo',
            name='otp',
            field=models.IntegerField(null=True),
        ),
    ]
