# Generated by Django 3.1.7 on 2021-04-10 12:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0033_auto_20210407_2301'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='delivery',
            field=models.CharField(choices=[('Morning', 'Morning'), ('Afternoon', 'Afternoon'), ('Evening', 'Evening')], default='Evening', max_length=255),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='vinfo',
            name='Category',
            field=models.CharField(choices=[('Grocery', 'Grocery'), ('Dairy', 'Dairy'), ('Electronics', 'Electronics'), ('Food', 'Food'), ('Medical', 'Medical')], max_length=255),
        ),
    ]
